package de.skash.movielist.core.network.model

data class ApiDetailedTvShow(
    val backdrop_path: String,
    val created_by: List<ApiPerson>,
    val episode_run_time: List<Int>,
    val first_air_date: String,
    val genres: List<ApiGenre>,
    val homepage: String,
    val id: Int,
    val in_production: Boolean,
    val languages: List<String>,
    val last_air_date: String,
    val last_episode_to_air: ApiEpisode,
    val name: String,
    val networks: List<ApiNetwork>,
    val next_episode_to_air: ApiEpisode?,
    val number_of_episodes: Int,
    val number_of_seasons: Int,
    val origin_country: List<String>,
    val original_language: String,
    val original_name: String,
    val overview: String,
    val popularity: Double,
    val poster_path: String,
    val production_companies: List<ApiProductionCompany>,
    val production_countries: List<ApiProductionCountry>,
    val seasons: List<ApiSeason>,
    val spoken_languages: List<ApiSpokenLanguage>,
    val status: String,
    val tagline: String,
    val type: String,
    val vote_average: Double,
    val vote_count: Int
)